### PR TITLE
Fix default resolution issue with empty module config

### LINKED ISSUE #1003: Exception with empty module config
Augury version (required): 1.2.12
Angular version (required): 2+

screen shot 2017-03-07 at 10 46 58 am

### PR DESCRIPTION
**Pull request by stevenkampen**
resolves #1003

### CODE REVIEW

**Comment by stevenkampen** [comment]
@rajinder-yadav @tyllrb Please review.

File: src/backend/utils/parse-modules.ts [hunk 1]
```diff
@@ -171,7 +171,7 @@ const _parseModule = (
     const providersFromModuleImports = [];
 
     // parse modules imported by this module
-    const flatImports = flatten((ngModuleDecoratorConfig.imports || {}) || []);
+    const flatImports = flatten((ngModuleDecoratorConfig || {}).imports || []);
```
Comment (rajinder-yadav) [inline src/backend/utils/parse-modules.ts]: :shipit:
