### PR TITLE
Fixes error message for non Angular apps.

### LINKED ISSUE #304: Display proper message If not Angular2 application
Several reasons as to when this message can be displayed:
1) This actually NOT and Angular 2 application
2) It is an Angular 2 application but NOT running in DEV mode

The message needs to be generic enough to cover the above scenarios

### PR DESCRIPTION
**Pull request by rajinder-yadav**
resolves #304

### CODE REVIEW

File: src/frontend/app.ts [hunk 1]
```diff
@@ -59,7 +59,7 @@ export class App {
   private selectedTab: Tab = Tab.ComponentTree;
   private subscription: Subscription;
   private tree: MutableTree;
-  private error: ApplicationError;
+  private error: ApplicationError = new ApplicationError(ApplicationErrorType.NotNgApp);
```
Comment (stevenkampen) [inline src/frontend/app.ts]: @rajinder-yadav Can we change this so this error scenario is explicitly indicated from the backend (or more acurately, the `ng-validate` script)? As it is now we get a flash of this error message while Augury is starting up which I think it a little yucky.

File: src/frontend/components/render-error/render-error.html [hunk 2]
```diff
@@ -14,6 +14,11 @@
...
       </p>
     </div>
+    <div *ngSwitchCase="ApplicationErrorType.NotNgApp">
+      <p>
+        This application is not an Angular application.
+      </p>
+    </div>
     <div *ngSwitchCase="ApplicationErrorType.ProductionMode">
       <p>
         This application is either not an Angular 2 application or is running in production mode
```
Comment (stevenkampen) [inline src/frontend/components/render-error/render-error.html]: @rajinder-yadav This message here probably needs to be changed since it's now specifically indicating that this application *is* in production mode.

File: src/frontend/app.ts (hunk 1 above)
Comment (rajinder-yadav) [inline src/frontend/app.ts]: I was't able to detect the flashing, but make sense to make the change.

File: src/frontend/components/render-error/render-error.html (hunk 2 above)
Comment (rajinder-yadav) [inline src/frontend/components/render-error/render-error.html]: We should be able to detect the Application is not Angular or it's not an Angular app in production mode. I'll consider reviewing once the changes are made to detect this from the backend.

**Comment by rajinder-yadav** [comment]
:shipit:
